steps:
  - read: remote_provider
    from: git.remote_provider
    fallback:
      from: env.TMPLR_REMOTE_PROVIDER
  - read: remote_owner
    from: git.remote_owner
    fallback:
      from: env.TMPLR_GIT_USER
      
  - read: project_name
    prompt: "Project name"
    choices:
      - From file:
          from: filesystem.rootdir
      - Custom:
          prompt: "Enter project name:"
          default:
            from: filesystem.rootdir

  - read: package_id
    prompt: "Package ID"
    choices:
      - From file:
          eval: "{{ filesystem.rootdir | kebab-case }}"
      - From project name:
          eval: "{{ project_name | kebab-case }}"
      - Custom:
          prompt: "Enter package ID:"
          default:
            eval: "{{ project_name | kebab-case }}"

  - read: workspace_name
    prompt: "Workspace name"
    choices:
      - From git username:
          from: remote_owner
      - Custom:
          prompt: "Enter workspace name:"
          default:
            from: remote_owner
      - None: ""
  
  - if: workspace_name
    read: package_identifier
    eval: "@{{ workspace_name | kebab-case }}/{{ package_id }}"
    else:
      read: package_identifier
      eval: "{{ package_id }}"

  - read: repository_url
    prompt: "Repository URL"
    choices:
      - From git:
          eval: "https://{{ remote_provider }}/{{ remote_owner }}/{{ package_id }}"
      - Custom:
          prompt: "Enter repository URL:"
          default:
            eval: "https://{{ remote_provider }}/{{ remote_owner }}/{{ package_id }}"
  
  - degit: Ptolemy2002/npm-bash-scripts/general
    to:
      path: "scripts"

  - update: "README.md"
  - update: "package.json"
  - update: "index.html"
  - update: "src/**/*.tsx"
  - update: "src/**/*.ts"
  - update: "src/**/*.less"
  - remove: "package-lock.json"
  - remove: "dist"
  - remove: "node_modules"